'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XbmcSkinEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down___12x11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down___12x11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property audio_cd_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audio_cd_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_controls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_controls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_controls1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_controls1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_controls2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_controls2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_details() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_details", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_details1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_details1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_details2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_details2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_details3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_details3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_pTime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_pTime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_pTime1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_pTime1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_exit_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_exit_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_exit_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_exit_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_mute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_mute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_mute_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_mute_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_mute_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_mute_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_next_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_next_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_next_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_next_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_open_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_open_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_open_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_open_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_partymode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_partymode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_partymode_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_partymode_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_partymode_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_partymode_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_partymode_selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_partymode_selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_pause_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_pause_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_pause_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_pause_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_pause_hover1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_pause_hover1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_play_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_play_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_play_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_play_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_playlist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_playlist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_playlist_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_playlist_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_playlist_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_playlist_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_previous_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_previous_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_previous_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_previous_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_remote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_remote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_remote_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_remote_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_remote_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_remote_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_repeat_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_repeat_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_repeat_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_repeat_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_repeat_selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_repeat_selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_shuffle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_shuffle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_shuffle_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_shuffle_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_shuffle_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_shuffle_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_shuffle_selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_shuffle_selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_stop_click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_stop_click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_stop_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_stop_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close1_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close1_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property configure_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configure_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language&gt;
        '''	&lt;mainform&gt;
        '''		&lt;connection&gt;
        '''			&lt;none&gt;Can&apos;t connect with XBMC&lt;/none&gt;
        '''		&lt;/connection&gt;
        '''		&lt;label&gt;
        '''			&lt;artist&gt;artist&lt;/artist&gt;
        '''			&lt;title&gt;title&lt;/title&gt;
        '''			&lt;album&gt;album&lt;/album&gt;
        '''		&lt;/label&gt;
        '''		&lt;playing&gt;
        '''			&lt;nothing&gt;No media playing&lt;/nothing&gt;
        '''			&lt;now&gt;Now playing &lt;/now&gt;
        '''			&lt;paused&gt;Playback paused&lt;/paused&gt;
        '''		&lt;/playing&gt;
        '''		&lt;dialog&gt;
        '''			&lt;lastfmLoveTitle&gt;Last.FM Love track&lt;/lastfmLoveTitle&gt;
        '''			&lt;lastfmLove&gt;This will add the currently playing track to your personal &apos;Loved tracks&apos; on Last.FM.\n\nAre yo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property english() As String
            Get
                Return ResourceManager.GetString("english", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property exit_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language&gt;
        '''	&lt;mainform&gt;
        '''		&lt;connection&gt;
        '''			&lt;none&gt;Impossible de se connecter à XBMC&lt;/none&gt;
        '''		&lt;/connection&gt;
        '''		&lt;label&gt;
        '''			&lt;artist&gt;artiste&lt;/artist&gt;
        '''			&lt;title&gt;titre&lt;/title&gt;
        '''			&lt;album&gt;album&lt;/album&gt;
        '''		&lt;/label&gt;
        '''		&lt;playing&gt;
        '''			&lt;nothing&gt;Aucun media en cours de lecture&lt;/nothing&gt;
        '''			&lt;now&gt;Lecture en cours&lt;/now&gt;
        '''			&lt;paused&gt;En pause&lt;/paused&gt;
        '''		&lt;/playing&gt;
        '''		&lt;dialog&gt;
        '''			&lt;lastfmLoveTitle&gt;Last.FM Love track&lt;/lastfmLoveTitle&gt;
        '''			&lt;lastfmLove&gt;This will add the currently playing track to your personal &apos;Loved tracks [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property francais() As String
            Get
                Return ResourceManager.GetString("francais", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property hide_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hide_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last_fm_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_fm_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last_fm_16x161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_fm_16x161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_hate5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_hate5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_love() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_love", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm_love1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm_love1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lastfm2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lastfm2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MainFormBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainFormBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MainFormBackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainFormBackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MainFormBackground2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainFormBackground2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize1_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize1_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mute_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mute_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mute_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_numpad_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_numpad_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_play_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_play_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_vol_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_vol_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property navigator_vol_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigator_vol_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;language&gt;
        '''	&lt;mainform&gt;
        '''		&lt;connection&gt;
        '''			&lt;none&gt;Kan niet verbinden met XBMC&lt;/none&gt;
        '''		&lt;/connection&gt;
        '''		&lt;label&gt;
        '''			&lt;artist&gt;artiest&lt;/artist&gt;
        '''			&lt;title&gt;titel&lt;/title&gt;
        '''			&lt;album&gt;album&lt;/album&gt;
        '''		&lt;/label&gt;
        '''		&lt;playing&gt;
        '''			&lt;nothing&gt;Er wordt geen media afgespeeld&lt;/nothing&gt;
        '''			&lt;now&gt;Speelt nu &lt;/now&gt;
        '''			&lt;paused&gt;Afspelen gepauseerd&lt;/paused&gt;
        '''		&lt;/playing&gt;
        '''		&lt;dialog&gt;
        '''			&lt;lastfmLoveTitle&gt;Last.FM Love track&lt;/lastfmLoveTitle&gt;
        '''			&lt;lastfmLove&gt;This will add the currently playing track to your personal &apos;Loved tracks&apos;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property nederlands() As String
            Get
                Return ResourceManager.GetString("nederlands", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property next_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next2_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next2_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openContextMenuArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openContextMenuArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openContextMenuArrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openContextMenuArrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause2_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause2_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pictures_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pictures_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play2_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play2_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play2_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play2_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reboot_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reboot_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property restart_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restart_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property send_media_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("send_media_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property show_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("show_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop2_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop2_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property url_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("url_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property video_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("video_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XBMC() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("XBMC", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property XBMClogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XBMClogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XBMClogo_90x90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XBMClogo_90x90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
